### ISSUE TITLE
这个例子为啥不展示与IAS通信呢？少了这部分就和SDK里面的RA差不多了

### ISSUE THREAD

**Issue by followinds** [GtBreeze/SGXRemoteAttestation#1]

**Comment by evenbily** [comment]
这个部分是用的socket做的，已经嵌入到代码中了，具体就在app里边实现的。

**Comment by evenbily** [comment]
具体代码是在 SGXRemoteAttestation/server/service_provider/network_ra.cpp

**Comment by evenbily** [comment]
这里只是做了一个简单的Server和Client通信的例子。因为一些原因没有向Intel申请IAS的证书，所以IAS证书验证没有代码实现，只是一个模拟的实现。
